# Lab notebook - week 2

### * A note about cell output - expressions vs. statements

In [31]:
# Some code fragments produce output, see the red "Out[?]" below - such fragments are called expressions.
5 + 2

7

In [12]:
# Other fragments produce no output. Such fragments are called statements. Not that there is no "Out[]" below this cell.
x = 5 + 2

In [24]:
# If you want to see the value of x, just write x on another line, "x" is an "expression" and produces the value of x as output
y = 3 + 7
y

10

In [21]:
# A cell only produces one output - that of the last expression in the cell
x  # value of x is not shown
y 

10

In [30]:
# If you want to see several values, output them from different cells or use print()
# note that print() produces text, but it is not labeled as Out[] (why?)
print(x)
print(y)

5
10


## NumPy basics
Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [1]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [6]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [66]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [7]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [8]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [44]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [111]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.01334854, 0.65479998, 0.73134173, 0.38249221, 0.85178481,
       0.55861644])

In [56]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([36, 12, 70, 46, 86, 52])

### Array properties

In [68]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [45]:
# The total number of elements
b.size 

6

In [46]:
# number of dimensions
b.ndim 

2

In [57]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [58]:
# Data type of the array
a.dtype

dtype('int32')

In [61]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [64]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


#### Convert a list into a numpy array

In [3]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [4]:
# your code here
x = np.array(lst)
x

array([5, 3, 8, 4])

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [5]:
# Feel free to add more cells
lst*3

[5, 3, 8, 4, 5, 3, 8, 4, 5, 3, 8, 4]

In [6]:
x*3

array([15,  9, 24, 12])

#### Create an array of 10 ones

In [9]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (including 50)

In [16]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of 10 random numbers between 0 and 5 (not integers)

In [18]:
arr = np.random.rand(10)*5
arr

array([3.57937897, 1.26627029, 2.37758703, 3.01527392, 2.37515325,
       0.60108559, 4.0565057 , 4.08989083, 3.62185509, 3.15960543])

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2

In [19]:
arr = np.linspace(0,2,num=11)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#### Create a 3 by 4 array of ones

In [20]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Create a 3 by 4 array of fives

In [22]:
arr = np.ones((3,4))*5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

#### Create a 3x3 matrix with values ranging from 0 to 8 (use reshape)

In [26]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Element selection
Using the following arrays `a` and `m`

In [30]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
m = np.arange(1,22).reshape((3,7))
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Create an array containing... 
#### the first 4 elements of a

In [33]:
arr = a[:4]
arr

array([10, 11, 12, 13])

#### the last 3 elements of a

In [37]:
arr = a[(a.size-3):]
arr

array([18, 19, 20])

#### The middle elements of a from 15 to 18 inclusive

In [42]:
arr = a[(a.size//2):(a.size//2+4)]
arr

array([15, 16, 17, 18])

#### The first column of m

In [52]:
arr = m[:,0]
arr

array([ 1,  8, 15])

#### The middle row of m

In [53]:
arr = m[1,:]
arr

array([ 8,  9, 10, 11, 12, 13, 14])

#### The left 3 columns of m

In [57]:
arr = m[:3,:3]
arr

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

#### The bottom-right 2 by 2 square

In [61]:
rows = np.array([[1,1],[2,2]], dtype=np.intp)
columns = np.array([[5,6],[5,6]], dtype=np.intp)
arr = m[rows, columns]
arr

array([[13, 14],
       [20, 21]])

#### (bonus) every other element of a  

array([10, 12, 14, 16, 18, 20])

#### Subtract 5 from each element of a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [104]:
# Hint
np.int8

numpy.int8